# Generated by Django 5.2.5 on 2025-08-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_alter_meal_carbs_alter_meal_fat_alter_meal_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image_url',
            field=models.URLField(default='default.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
